name: Create Release and Deploy to Railway 

# trigger
on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

# Jobs in the workflow
jobs:
  # job name, 
  create_release_and_deploy:
    # OS that this job will be running on
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}

    # list of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"
    - name: List runner name
      run: echo "runner os - ${{ runner.os }}"

    - name: branch name
      run: echo "branch name - ${{ github.ref_name }}"
    - name: Checkout the current repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }} 
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit: ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@main
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        github-token: ${{ secrets.GH_TOKEN }}

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                "type": "plain_text",
                "text": "DipSA55 CI/CD Assignment Submission",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Name:*\nYeo Min Xiu Sherlin"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Matriculation:*\nA0116582E"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Email:*\n<e1043503@u.nus.edu|e1043503@u.nus.edu>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Repository:*\n<${{ github.repositoryUrl }}|${{ github.repositoryUrl }}>"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Deployment:*\n<${{ github.deployment_url }}|${{ github.deployment_url }}>"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "<${{ github.deployment_url }}|Open Application>"
                }
              ]
            } ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK