name: Workflow (on push branch v1.0)

# trigger
on:
  push:
    branches:
    - "v[0-9].+([0-9])"

# Jobs in the workflow
jobs:
  # job name, 
  workflow-on-push:
    # OS that this job will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"
    - name: List runner name
      run: echo "runner os - ${{ runner.os }}"

    - name: branch name
      run: echo "branch name - ${{ github.ref_name }}"
    - name: Checkout the current repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: List my current directory after checkout
      run: ls -la 